# .github/workflows/main.yml

name: CI/CD Pipeline

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # The job will run on a fresh Ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code so the workflow can access it
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using the secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the Frontend Docker image
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend/HomeService # The path to your frontend's Dockerfile
          push: true
          tags: nehaa3/home-service-frontend:latest # <-- REPLACE THIS